FROM golang:latest

ARG GODADDY_APIKEY
ARG GODADDY_APISECRET
ARG GODADDY_DOMAIN
ARG BASELINE_RECORD

ENV GODADDY_APIKEY=${GODADDY_APIKEY}
ENV GODADDY_APISECRET=${GODADDY_APISECRET}
ENV GODADDY_DOMAIN=${GODADDY_DOMAIN}
ENV BASELINE_RECORD=${BASELINE_RECORD}

RUN mkdir /app
ADD . /app
WORKDIR /app
RUN go build -o main .
CMD ["/app/main"]
