apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: godaddy-dynamic-dns-cronjob
spec:
  ######## at every fifteenth minute
  schedule: "*/15 * * * *"

  ######## Number of containers (jobs) to keep after completing successfully
  ######## (containers are simply powered off)
  ######## DEFAULT IS 3
  # successfulJobsHistoryLimit: 0

  ######## Number of containers (jobs) to keep after failure
  ######## (containers are simply powered off)
  ######## DEFAULT IS 3 (I believe, I think I remember reading
  ######## that, but have not confirmed)
  # failedJobsHistoryLimit: 0

  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: godaddy-dynamic-dns
              image: oze4/godaddy-dynamic-dns:latest
              env:
                - name: GODADDY_APIKEY
                  value: "-"
                - name: GODADDY_APISECRET
                  value: "-"
                - name: GODADDY_DOMAIN
                  value: "-"
                - name: BASELINE_RECORD
                  value: "-"
          restartPolicy: OnFailure
